apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: movie-secret-store
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: tye/.dapr/secrets/movie-secrets.json   # runs daprd with working directory of the root folder, it seems
    - name: nestedSeparator
      value: ":"